FROM tomcat:8.5-jre8

# Maintainer
MAINTAINER "sudheer veeravalli <veersudhir83@gmail.com>"

# Copy war file to tomcat webapps folder 
COPY sample.war /usr/local/tomcat/webapps/

# Make port 80 available to the world outside this container
EXPOSE 80
