version: "3"
services:
  web:
    image: veersudhir83/pycountvisits:latest
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8091:80"
    networks:
      - webnet
networks:
  webnet:
