version: "3"
services:
  web:
    #build: .
    image: tommy:latest
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "9999:80"
    networks:
      - webnet
networks:
  webnet:
