version: "3.0"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: veersudhir83/<tommy8.5:tag>
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "8090:8080"
