version: "3.0"
services:
  web:
    build: ./
    image: 127.0.0.1:5000/devops-web-tommy-stack:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "8090:8080"
