version: "3.0"
services:
  web:
    build: ./
    image: 127.0.0.1:5000/devops-web-tommy-stack:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "8090:8080"

version: '3'
 
services:
 
  main:
    image: vfarcic/go-demo
    environment:
      - DB=db
    networks:
      - proxy
      - default
    deploy:
      replicas: 3
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/demo
        - com.df.port=8080
 
  db:
    image: mongo
    networks:
      - default
 
networks:
  default:
    external: false
  proxy:
    external: true
